%Function for performing a bilinear interpolation of DSM
%Image input is Matlab .MAT file. The file is generated by the following
%command (original image in .TIFF with .TFW world file):
% 
% % DSM = imread('dsmpath');
% % worldFileName = getworldfilename('dsmpath');
% % save('DSM.mat','DSM');
% 
%Other inputs are:
% a.Resolution and X Y planar coordinates of the upper left corner of the 
%   DSM file. How to extract them:
% 
% % R = worldfileread(worldFileName, 'planar', size(DSM));
% % X0tiff = R.XWorldLimits(1,1);
% % Y0tiff = R.YWorldLimits(1,2);
% % ResTiff = R.CellExtentInWorldX;
% 
% b. X Y planar coordinates to be interpolated
%
%Written by Arnadi MURTIYOSO 
%ifp Stuttgart & INSA de Strasbourg
%Last update: 24/06/15

function [Zc] = bilineinter (X,X0tiff,Y0tiff,ResTiff,X1,Y1)
%CALCULATE PIXEL LOCATION
xc = (X1-X0tiff)/ResTiff;
yc = (Y0tiff-Y1)/ResTiff;

%DETERMINE NEIGHBOURS
%2---a---3
%|   |   |
%b---c   |
%|       |
%1-------4
x1 = floor(xc);
y1 = floor(yc);

x2 = x1;
y2 = y1+1;

x3 = x1+1;
y3 = y1+1;

x4 = x1+1;
y4 = y1;

xa = xc;
ya = y2;

xb = x1;
yb = yc;

%BILINEAR INTERPOLATION 
Za = (x3-xa)/(x3-x2)*X(y2,x2)+(xa-x2)/(x3-x2)*X(y3,x3);
Zb = (x3-xa)/(x3-x2)*X(y1,x1)+(xa-x2)/(x3-x2)*X(y4,x4);

Zc = (y1-yc)/(y1-y2)*Za+(yc-y2)/(y1-y2)*Zb;
